version: '3.8'
services:
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto
    restart: unless-stopped
    ports : ['1883:1883']
    
  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    container_name: portainer
    restart: always
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  influxdb:
    container_name: influxdb
    environment:
      - INFLUXDB_DB=home
      - INFLUXDB_ADMIN_USER=breaddb
      - INFLUXDB_ADMIN_PASSWORD=QWaziKi6MuOt
    image: hypriot/rpi-influxdb
    restart: unless-stopped
    volumes: 
      - '/home/influxdb:/var/lib/influxdb'
    ports : 
       - '8086:8086'

  chronograf:
    image: chronograf:latest
    restart : unless-stopped
    container_name: chronograf
    ports:
      - '8888:8888'
    volumes:
      - chronograf-storage:/var/lib/chronograf
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=breaddb
      - INFLUXDB_PASSWORD=QWaziKi6MuOt

  telegraf:
    image: telegraf
    container_name: telegraf
    restart: always
    links:
      - influxdb
      - mqtt
    depends_on:
      - influxdb
    environment:
      HOST_PROC: /rootfs/proc
      HOST_SYS: /rootfs/sys
      HOST_ETC: /rootfs/etc
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro





volumes:
    portainer_data:
    chronograf-storage:

